<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WinDbgBridge</RootNamespace>
    <AssemblyName>WinDbgBridge</AssemblyName>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="windbg-bridge.png" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DbgX.Interfaces">
      <HintPath>..\..\lib\DbgX.Interfaces.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="DbgX.Interfaces.Internal">
      <HintPath>..\..\lib\DbgX.Interfaces.Internal.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="DbgX.Util">
      <HintPath>..\..\lib\DbgX.Util.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Fluent">
      <HintPath>..\..\lib\Fluent.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.ComponentModel.Composition">
      <HintPath>..\..\lib\System.ComponentModel.Composition.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
